version: '3.8'
services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - sendkite
networks:
  sendkite:
    